### ISSUE TITLE
 error: ‘ios’ has not been declared

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/TestBenchGenerator#4]
I'm using `io_reset` branch as well as the latest `run_tgb.csh` from `CGRAGenerator` branch.
Attached `harness.cpp` (renamed to `.txt`).

Shouldn't this line:
https://github.com/StanfordAHA/TestBenchGenerator/blob/8210ea9e25f85b236e612cb0dacd3f9a50c86fdf/generate_harness.py#L211
be `std::ios::binary`?

```
$ verilator -version
Verilator 3.916 2017-11-25 rev verilator_3_914-65-g0478dbd
$ g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
```

[harness.txt](https://github.com/StanfordAHA/TestBenchGenerator/files/2344108/harness.txt)

**Comment by leonardt** [comment]
Does changing it work for you? If so, submit a pull request with the fix please

**Comment by Kuree** [comment]
Yes, adding `std::` works. See https://github.com/Kuree/cgra_test/blob/master/scripts/cgra_gen.sh#L17.

I will submit a PR.

**Comment by leonardt** [comment]
@Kuree sounds good, I think this is probably an issue with the compiler you're using (or rather, the compilers currently using TBG don't seem to care, maybe they include the `ios` namespace by default?), anyways I doubt this change will cause any problems with are existing flows.

**Comment by leonardt** [comment]
Note: this is likely an issue introduced by newer GCC versions

**Comment by leonardt** [comment]
Fixed in https://github.com/StanfordAHA/TestBenchGenerator/pull/6
